name: ci

on:
  push:
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: nix flake check
        run: nix flake check --all-systems --print-build-logs
